### ISSUE TITLE
No need to place executable in git repo.

### ISSUE THREAD

**Issue by Vui-Chee** [nyi2thwin/gitpeek#1]
I am no expert in Golang but I am pretty sure anyone can run `go install` in the main repo which should generate the binary (if GOBIN is set).

**Comment by Vui-Chee** [comment]
Another possible extension of this is to convert this repo into a Golang plugin, such as allowing `go install github/nyi2thwin/gitpeek`.

**Comment by nyi2thwin** [comment]
yeap, but I just put it there so that people can just run it without go or compile with go build or go install. But as you suggested I think I should create a release and put the executable at the release.
